### ISSUE TITLE
Предложения

### ISSUE THREAD

**Issue by pluzanov** [le0pard/postgresql_book#28]
Алексей, спасибо за книгу и регулярные обновления.
Ниже несколько пожеланий, чтобы сделать её еще лучше.

1. В главе "Репликация".

"В частности, конфликты могут возникать по поводу того, в каком порядке должны применяться обновления. Например, предположим, что в результате выполнения транзакции А происходит вставка строки в реплику X, после чего транзакция B удаляет эту строку, а также допустим, что Y — реплика X. Если обновления распространяются на Y, но вводятся в реплику Y в обратном порядке (например, из-за разных задержек при передаче), то транзакция B не находит в Y строку, подлежащую удалению, и не выполняет своё действие, после чего транзакция А вставляет эту строку. Суммарный эффект состоит в том, что реплика Y содержит указанную строку, а реплика X — нет."

Суть конфликта не понятна. Вообще непонятна.

2. В описании потоковой репликации ни слова про слоты репликации и настройку обратной связи.

Это важный функционал репликации. Кстати там можно и про конфликты потоковой репликации рассказать.

3. В главе "Бэкап и восстановление PostgreSQL"

Нет про горячее резервное копирование.
Например, про pg_basebackup.

4. Нет ничего про настройку autovacuum.

Крайне важная тема.

5. В главе про dblink можно сказать, что модуль позволяет эмулировать автономные транзакции.

**Comment by le0pard** [comment]
@pluzanov благодарю за пожелания.

**Comment by le0pard** [comment]
Перенес в TODO: https://github.com/le0pard/postgresql_book/commit/4c8c03c0d8cc15a352a0b524daaa0f0d8cbbcb12
