### ISSUE TITLE
Не отображаются SQL-запросы в HTML-версии

### ISSUE THREAD

**Issue by vsolovyov** [le0pard/postgresql_book#29]
Например, [размер объектов в базе данных](http://postgresql.leopard.in.ua/html/#%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2-%D0%B2-%D0%B1%D0%B0%D0%B7%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85) - нет запроса, только результат (и ниже тоже)

В исходнике https://github.com/le0pard/postgresql_book/blob/master/postgresql_tips.tex есть упоминание:

```
\lstinputlisting[language=SQL,label=lst:snippets1,title=snippets/biggest\_relations.sql]{example_code/snippets/biggest_relations.sql}
```

**Comment by le0pard** [comment]
Это проблема pandoc, в pdf все есть.

**Comment by le0pard** [comment]
pandoc 2.0 не помог :)

**Comment by le0pard** [comment]
@vsolovyov fixed in 5.1.4
