### ISSUE TITLE
Блоки кода в epub формате

### ISSUE THREAD

**Issue by SysAlex** [le0pard/postgresql_book#43]
Приветствую.
Есть проблема в epub формате на Eink читалках PocketBook - блоки кода не переносятся и уползают за пределы экрана.

К примеру на странице "Возможности индексов", сразу вначале главы.

<img src="https://habrastorage.org/web/4e2/158/f31/4e2158f3182b4c0c809551395f8f53e3.jpg"/>

**Comment by le0pard** [comment]
Это к http://pandoc.org/
