### ISSUE TITLE
Возможно опечатка

### ISSUE THREAD

**Issue by vsvasya** [le0pard/postgresql_book#52]
Добрый день!

Не является ли опечаткой фраза "десятки миллионов столбцов" в главе 2.2?

"С другой стороны, приложения для поддержки
принятия решений с сотнями строк в каждом запросе и десятками мил-
лионов столбцов в таблицах фактов часто требуют work_mem порядка 500
МБ."

P.S.: Спасибо за книгу!

**Comment by le0pard** [comment]
@vsvasya fixed by https://github.com/le0pard/postgresql_book/commit/a8f4b4d654dd2599597abe298f1ecc86e2f745f9
